apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nWtTCBYLLQqtp/zLU4K/xocfSRW7QweAGPsBrHvPWXEvVXqWx7BZtw==,iv:oySBZlak/XTuN3gMW3ELMw8/XpJd2I2bmfe4h6jclao=,tag:zb6cc1aa8s4LGOTJJ70sBg==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcVcvNnZXS1dWY3RSWkp3
        cDc3dm1tZThreFh0K0xzSG4yQWU4WWZ6UUQ0CkUrZmFFRzA3a25tUlV3cXo4S3JH
        eFdrTFdLbU1rTGIrekhlV216UjZxbE0KLS0tIHl3UFp4aUZlZDltMHlaVHJCVTRz
        UmNmWVJ0a25YcWc5akdOTXN6aDkvY28K9XgmCwtvaMmQ4TF8cdo6Y5uTlMyaUHSe
        pIC86Bawg2x6her2fXlBdqUDcxCu9+7mepb8BZnEOF+rIJOB7Iz5FA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:56:30Z"
  mac: ENC[AES256_GCM,data:c2GHsiAExIgBo/nB2W6IMIEYhjsphxcjn+p+vcC7W93GdFCHcdVXvEUiBJrC/q2lwLj4BFx6PMiGB9PAvsbVGKQZ1aOCcewgEYNw6JAcWeMq1qLwGFlHCZM0kNmsB0++AYEDs2bMYFwbtcJuFla7nM6YoGDQlNi5S+36x3x0ZiQ=,iv:8vMayks17h/W29KDM/pZQkn01/Xbv7xY8k96tGoAeFA=,tag:hODL4mJIFZUY33UvlMQLBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
