apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:W6WATdtlWfG5ekAL,iv:R3aVZDHpdacErU5UlFTfD9w7Agu5HCezgQ+JILm/z6I=,tag:gdKYX3KDk8H+tMSk5pmAZQ==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ0Y3OGVvY2hLTWpoNXZL
        QTdzeWZ3NjdlRysyUWdBbXNtbHZVTUhkZ0drCmdkVG1TWXpPaG1TQ3VXVVNKWE1i
        RCtMSGdSUjNTM0kwWm85bHB0T29XczAKLS0tIGZhTWpZc2J5akpTL3JxeGZuaHhQ
        aE11aUJJSlhsWENNWHpQSm1kdHVoTHMKtmLub99xZA4RBx5DxTyxo4dnPI8Yv0n8
        sbBgS7TAP3XKSAQ8BsJ/9pqv8o/cfzdejE+tP88eYjjizS1WySAAKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:56:30Z"
  mac: ENC[AES256_GCM,data:NH5Qg966iux3M+XQPUit6RBcnchnpoYHNIlnRpdgHDI/pIYApsrC0ilFEsH6l3H4qK4U/SLvkkLsyfy26RGNrq0IaJ3upO1Z8n031B4ZYAIbQeWRhc8DsTEG+pKDNirZML5TucDmaLtX43buQgWTrhfIsT+Y2wHu8v+Xbn5d8Gg=,iv:AMG2ee92bELbRyRHU2LzmGcYIESGure9uQrNnmnqR1w=,tag:+c7Uz+dlnZ1TQsC/B5VkJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
