apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CE3IndOhH3/CXRh0aF9mZuCQnBD9lW4EhgMaoP4FPCM=,iv:D2w0exdw3KovsoJgwNr5OUnw1HroNGdnfb2e7kzcETE=,tag:z660JUVtNO1xtTD6tzUgcQ==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZGlTT24vckYxeU90bnQv
        aGtIdEQrcDJndU9wOGtvbnE1MUMvakZjVW13CkV2NHV3TlhFKzU0VGdJWHR3T3Bs
        UENOWDJEcFRaVnVBeFJzckFMNGRhVmcKLS0tIFZnSXRrT3RBZWUwaDVYTThTM2to
        anpiZ1AvUzlwK1MvdW1mN1NxSnpCZjAKJBIDyqwcVwE6K9Kzy5KTGS8C2C0iwBIl
        6JVubSzO7QcvESbVTlLXO0qe/j26NDc2TRZ1tbyLWItMl66ekdatUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:56:30Z"
  mac: ENC[AES256_GCM,data:/TykAdCnMMK8S35j03YWxiwwEHSEq/kZGCse1NqvFi1S52sC97MSE6euObkewet9iZEt4LIucp6hwX3iKxtG4AjqmQCi5P3SMDeOvIXAWNNT1Pt/pji+Ty8EkFY5fE1MN7zo1cC2BNmzZ0QjX87DFj6cfrz2rrfrqHzYuIlDcFg=,iv:60rKzQgQ4rc561I0rOy97Dg93baSgGCWeLfPT6m0MkQ=,tag:H/ZyxzZC6qPJf5mJua7MFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
