apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:oIZc11IfqIv45enrZB8GllbIlXW5yVOYttYjClbSB/GLVERJEdMRZMYz9kbVZ+e8xbjwMG0l9YJLo1C/tPlc429qFvuP2ds5J3Cc4v0EVrtcEw0CApIvpllmJw/j0Qf5R4I6+ypsBJM7QkgmQ+F3X/tQSbE9pH6wihZPPU/rPJcRyIONfjrP13PlblFAumxQVBg6030k55YAUxDK82HRTZn1LlQPtn9KBy+UzGCubtJBtSVz,iv:cLjmzegsRzhyF6pjXBkJTIhsvfpCVVKroAqIvjCkUHg=,tag:T0lr8Gz9lSiHPBeLr7Dc4g==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUW1JVWU4bjYwOTVjTnM1
        Ti84bXdDOFp6cElxUG5DSTErRklzZXBzZXh3CmMyRWg0ZGFqUWJZd20rNHV5N0sr
        SUJWQzNGd1JyUkNUc0hCSHhBZ0RpMjAKLS0tIDlNT2VVWEJ1cjVMZURPWXQ4MkJy
        NURHVHNaMnEyOWUvaTc1TFRtTTFaanMKt2+l7qi3/J9gLXiB3PLRhPJ65u6T58Jt
        A1skPvKHyms3WH3YmqBOpxE+BgvBHMDiyCpPa/+X20wiwvYM3+Dd/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:56:30Z"
  mac: ENC[AES256_GCM,data:HDdr3r+8M3KwR+nbwPYn9A3Do8U4i27elajVDjrAXljy1iDleHFQHHKzLDD+0v1JMwY2P7+c1EeP84WcBLBTRdnFi2IQbIG8zoFNFE5lULODTRHDp5w+20rfMaqLdPzyvU8xLlxTMs8+Dl/1jLhTlSLrkepAENMItg3VjebqdO8=,iv:MGhTlb4KIqyTlxBxrGKwu6EZQvUpuj4UDuwcumFCxo8=,tag:qyo2DDm1h18cL79q2hYUCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
