apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PbcSBjg3yZwz55e/mviK7AT8xgzANfNvWiBG2u4GmpYLg7N7HM/dMQ==,iv:q6fi2an2+6CWOVYYOriSOfbsbTBsmc1E1mNZdJrHQoU=,tag:UAFYR2HNzX1javZZQw61hw==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbHFsZXRIQnB5WWtwd3Vt
        b29nTjdaUm16Y3hwTmlMYnFNcXpLQVVEbnl3CkJnYnZKajk5SUFNMEl3bXJZL2V0
        bDd1LzdFTEg5NXdPcm52ZDVKTGNVWGcKLS0tIHlsTmVwN2l3NkJ3YW5nVFIyUzg3
        ckRxZzg5dEFrU1l6K29DZlFBMUFtL1EKIqpnxfNRRQMRLpxXtcSs12ETUuAkpIM8
        Ftq23ZVQVdGoFtvQjvGQLSAyG1kUSV2UlXm6ZRhKMmMvYPpQS4cNWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:56:30Z"
  mac: ENC[AES256_GCM,data:U/rTUWleB/LElEmJaeAWuobSpuEV+bM6Pze4oTo/EVBOKTuYrHhYgjY4bV29PEH+8Q3rFaXA5AGnfi0fQ0640CogVBI6QwW+IbkT8ePVlWtnMhWw8slU+wWYBBdUVjbAlmAS8IZboHoxEu53H3ue6b/L0aLfaEn5Wl6FbhJAJ04=,iv:LAG4Kysi4jfEYZ/XvN5Etvco9Bt3pZkvikN+11h1Ozk=,tag:DMPJ4jB9xc21wH1PjbjAtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
