apiVersion: v1
kind: Secret
metadata:
  name: omgbot-secrets
  namespace: default
type: Opaque
stringData:
  DISCORD_TOKEN: ENC[AES256_GCM,data:qa69PvZsqM3Y0/N8qiclfvGelNf+KKTQTJuuBkGz3LGfyYhVnD05/VXXIRlKF1yM+VU17HvH/KRAZ9k4BiSrjJ6K1CEajsES,iv:Fn+iYPU+AalavL40DF5VctYHG8cTHz2JUwQIo0c4umA=,tag:PrTBLfBW6VbsrCYwKdqnjA==,type:str]
  DISCORD_GUILD: ENC[AES256_GCM,data:hgsNFvkXCranLKNiLQDxQruaFQ==,iv:D/b8gSAX10vCtmBgvaQ8pfpPL7lH3r6ml1WdjbIuPM4=,tag:EjyK4QpiRnCPmxBn0MBDAQ==,type:str]
  OMG_USERNAME: ENC[AES256_GCM,data:Xxp1EdCRjg==,iv:iA7JPirsxozWYVYi4b5+BHOCewF2VFSc1g81DKSVTe4=,tag:kMhD0Sl4gyhXhJ0ac62wKw==,type:str]
  CHANNEL_ID: ENC[AES256_GCM,data:aWpJxqnBQCBkcjtqeDJzw0dh/A==,iv:Glptf3AjVy7WmuGeqGjKKhh7ncehcnB9NLZACuRAg04=,tag:nlKFIsKL/EvLzUzU8YDdMQ==,type:str]
  MY_NAME: ENC[AES256_GCM,data:qK9A+g==,iv:BpgQF6eou2z7aTEs0RG6pstbZQYMeWki1+2cfMbZ+gI=,tag:vLDK6TMMkhIx6PCMPiFDQQ==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYkVocTZLckw2SnBvT1Vk
        eWdsQ2wrZENucWNJckM4NHFVZWlWK2NPQVI4CklWUnBFaXBmQUhSUFJBQWVxTUlN
        OG5Jck1DdVpwVjZkQ2I5TXEzNmx4M00KLS0tIFZaSmdMSXBwc0toM3BQWm1oN3Ns
        bzNKVCtaRnNtV0g0QTFXZXArcHppVFkKCbm1lksCRNoYm9MHRkYathbaF6yu/s5x
        fqjaHTKcRUakL8knFHZvT4wFm/xsr4PsDZ4g9B6I9W7RfovJsC6YdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T18:15:59Z"
  mac: ENC[AES256_GCM,data:zgYoEz1+T7QvgTna221Z/HVZvPLUENkT+C1bozr2imOfbKAwlfEP6ObKyvN8urBTVZpa9XCzMlziST843vrrOMsoO1NDrer+4V3tVTqWK+XsPFfLXiMc+8oCMou/5zuYAFizag5wJN/+tHLDJX+jdfS/6L+E2OOt/fq4cDkzBeM=,iv:ndahFsgBVJXmAbQJQ26BDk3ZdMykwsiXILTvY29Umic=,tag:V2Qf25XaGaxJIcvjk4l0Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
